import os
import smtplib
import logging
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from datetime import datetime
from dotenv import load_dotenv

load_dotenv()

def send_email_alert(order_details: dict, prediction: dict) -> bool:
    email_user = os.getenv("EMAIL_USER")
    email_password = os.getenv("EMAIL_PASSWORD")
    receiver_email = os.getenv("ALERT_RECEIVER_EMAIL")

    if not all([email_user, email_password, receiver_email]):
        logging.error("Email credentials missing. Cannot send email alert.")
        return False

    order_id = order_details.get("id")
    customer_name = order_details.get("customer_name")
    current_status = order_details.get("current_status")
    
    breach_prob = prediction.get("breach_probability", 0) * 100
    remaining_sla = order_details.get("remaining_sla_days", 0)
    recommendation = prediction.get("recommendation", "No recommendation.")
    
    timestamp = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")

    subject = f"[Eluno AI] SLA Breach Alert - Order #{order_id}"

    html_body = f"""
    <html>
      <body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333;">
        <h2 style="color: #d9534f;">🚨 Eluno AI - SLA Breach Alert</h2>
        <table style="width: 100%; max-width: 600px; border-collapse: collapse;">
          <tr>
            <td style="padding: 8px; border: 1px solid #ddd; font-weight: bold;">Order ID:</td>
            <td style="padding: 8px; border: 1px solid #ddd;">{order_id}</td>
          </tr>
          <tr>
            <td style="padding: 8px; border: 1px solid #ddd; font-weight: bold;">Customer:</td>
            <td style="padding: 8px; border: 1px solid #ddd;">{customer_name}</td>
          </tr>
          <tr>
            <td style="padding: 8px; border: 1px solid #ddd; font-weight: bold;">Current Status:</td>
            <td style="padding: 8px; border: 1px solid #ddd;">{current_status}</td>
          </tr>
          <tr>
            <td style="padding: 8px; border: 1px solid #ddd; font-weight: bold;">Breach Probability:</td>
            <td style="padding: 8px; border: 1px solid #ddd; color: #d9534f; font-weight: bold;">{breach_prob:.0f}%</td>
          </tr>
          <tr>
            <td style="padding: 8px; border: 1px solid #ddd; font-weight: bold;">Remaining SLA:</td>
            <td style="padding: 8px; border: 1px solid #ddd;">{remaining_sla} days</td>
          </tr>
        </table>

        <h3 style="margin-top: 20px;">AI Recommendation:</h3>
        <p style="background: #f9f9f9; padding: 15px; border-left: 5px solid #5bc0de; font-style: italic;">
          {recommendation}
        </p>

        <p style="margin-top: 30px; font-size: 0.9em; color: #777;">
          Generated by Eluno AI Operations Assistant<br>
          Timestamp: {timestamp}
        </p>
      </body>
    </html>
    """

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = email_user
    msg["To"] = receiver_email

    part = MIMEText(html_body, "html")
    msg.attach(part)

    try:
        # Using Gmail SMTP by default. Update if a different provider is needed.
        server = smtplib.SMTP("smtp.gmail.com", 587)
        server.starttls()
        server.login(email_user, email_password)
        server.sendmail(email_user, receiver_email, msg.as_string())
        server.quit()
        logging.info(f"Email alert sent successfully for Order #{order_id}")
        return True
    except Exception as e:
        logging.error(f"Failed to send email alert for Order #{order_id}: {e}")
        return False
